# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI Action - Deploy Resource Group with az cli
        uses: Azure/cli@v1.0.7
        with:
           inlinescript: |
              az deployment sub create --location "West Europe" --template-file ./arm-templates/resourcegroup.json



